models:
  - model: kurakurai/Qwen3-0.6B-Instruct
    parameters:
      weight: 0.5
  - model: kurakurai/Luth-0.6B-Scholar-checkpoint-136
    parameters:
      weight: 0.5
merge_method: linear
dtype: bfloat16