[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "french-slm"
version = "0.1.0"
description = "French SLM."
authors = [
  { name = "KuraKura AI"},
]
requires-python = "==3.12.*"
dependencies = [
  "transformers==4.51.3",
  "datasets==3.5.0",
  "wandb==0.19.11"
]

[tool.uv]
package = false
