model:
  model_name: "Qwen/Qwen3-0.6B"
  dtype: "bfloat16"
  gpu_memory_utilization: 0.8 

model_parameters:
  temperature: 0.0

extras:
  enable_thinking: true
  answer_token: "</think>"  
  use_chat_template: true
  system_prompt: "Vous êtes un assistant utile."
  num_runs: 1
  output_dir: "results/"
  save_details: true
  push_to_hub: false

tasks:
  # - "community|ifeval-fr|0|0"
  # - "community|gpqa-diamond-fr|0|0"
  # - "community|bbh-fr|0|0"
  # - "community|hellaswag-fr|0|0"
  # - "community|boolq-fr|0|0"
  # - "community|mmlu_fr|0|0"
  # - "community|musr-fr|0|0"
  # - "community|math-hard-fr|0|0"
